import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";

component TopBar {
    callback fetch <=> fetch.clicked;
    in property<string> status: "";
    height: 3rem;
    Rectangle {
        width: 100%;
        height: 100%;
        background: gray;
        HorizontalBox {
            alignment: start;
            fetch := Button {
                text: "Fetch new catgirl";
                primary: true;
            }
            Button {
                text: "Download into computer";
                primary: true;
            }
            Button {
                text: "Copy to clipboard";
                primary: true;
            }
            Text {
                text: status;
                font-size: 36pt;
                vertical-alignment: center;
                color: red;
            }
        }
    }
}

component Catgirl {
    in property <image> img;
    width: 95%;
    height: 95%;
    Rectangle {
        background: black;
        Image {
            width: 100%;
            height: 100%;
            source: img;
            image-fit: contain;
        }
    }
}

export component AppWindow inherits Window {
    callback fetch <=> tb.fetch;
    in property<string> status <=> tb.status;
    in property<image> img <=> cg.img;
    title: "jantar1154's catgirl downloader!";
    min-width: 640px;
    min-height: 480px;
    background: rgb(15, 20, 20);
    VerticalBox {
        y: 0;
        x: 0;
        alignment: start;
        tb := TopBar {}
        cg := Catgirl {}
    }
}